### ISSUE TITLE
Hugo serve won't run the theme

### ISSUE THREAD

**Issue by writeson** [derme302/triple-hyde#12]
Hi,
I'm VERY new to Hugo and I'd like to use the triple-hyde theme, but I'm having a problem. I think it's related to getting the SCSS to compile, but I'm not sure. When I follow the installation instructions and run "hugo serve" I get this error:

hugo serve
Watching for changes in /Users/dfarrell/tmp/my_blog/{archetypes,assets,content,data,i18n,layouts,static,themes}
Watching for config changes in /Users/dfarrell/tmp/my_blog/hugo.toml
Start building sites … 
hugo v0.122.0-b9a03bd59d5f71a529acb3e33f995e0ef332b3aa+extended darwin/amd64 BuildDate=2024-01-26T15:54:24Z VendorInfo=brew

Built in 259 ms
Error: error building site: TOCSS: failed to transform "scss/triple-hyde.scss" (text/x-scss): "/Users/dfarrell/tmp/my_blog/themes/triple-hyde/assets/scss/triple-hyde.scss:3:1": File to import not found or unreadable: font-awesome/assets/stylesheets/font-awesome.

Any help would be greatly appreciated.

Doug

**Comment by ddpruitt** [comment]
I'm having the same issue with the font-awesome submodule.  If I clone hugo my site then run 

`git submodule update --init --recursive`

I get the following output:

> Submodule 'themes/triple-hyde' (https://github.com/derme302/triple-hyde.git) registered for path 'themes/triple-hyde'
> Cloning into 'C:/Users/darre/sources/ddpruitt.github.io/themes/triple-hyde'...
> Submodule path 'themes/ananke': checked out '91df000ca82769a7578df81fa142d1a18e446bc0'
> Submodule path 'themes/triple-hyde': checked out '085c451bd14bdcd1ea04428aece554c0c4b4f4d4'
> Submodule 'assets/scss/font-awesome' (git@github.com:FortAwesome/font-awesome-sass.git) registered for path 'themes/triple-hyde/assets/scss/font-awesome'
> Cloning into 'C:/Users/darre/sources/ddpruitt.github.io/themes/triple-hyde/assets/scss/font-awesome'...
> Host key verification failed.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of 'git@github.com:FortAwesome/font-awesome-sass.git' into submodule path 'C:/Users/darre/sources/ddpruitt.github.io/themes/triple-hyde/assets/scss/font-awesome' failed
> Failed to clone 'assets/scss/font-awesome'. Retry scheduled
> Cloning into 'C:/Users/darre/sources/ddpruitt.github.io/themes/triple-hyde/assets/scss/font-awesome'...
> Host key verification failed.
> fatal: Could not read from remote repository.

When I initially added the triple-hyde theme I didn't get this problem, it was only after I tried to clone my hugo site to another machine.

**Comment by ddpruitt** [comment]
After some checking I found that the URL in the .gitmodules and in the .git/config are set to:

git@github.com:FortAwesome/font-awesome-sass.git

If they are changed to:

https://github.com/FortAwesome/font-awesome-sass.git

then the submodule can be downloaded using 

`git submodule update --init --recursive`

For reference:  https://stackoverflow.com/questions/13509293/git-fatal-could-not-read-from-remote-repository

I don't fully understand why the url got changed but I am able to get past the issue on my local machine..

**Comment by writeson** [comment]
Darren,

Thanks very much for the info and links! I modified the files you mention
and now the theme runs. :)

Again, thanks,
Doug

**Comment by derme302** [comment]
Interesting, I went back and forwards on this one but I made the assumption anyone with Git installed would also have `ssh`. I guess as the readme specifies using `https` we should keep it consistent.
